export const MOVE_TABLE = "MOVE_TABLE";
export const ADD_AVAILABLE_TABLE = "ADD_AVAILABLE_TABLE";
export const ADD_BOARD_TABLE = "ADD_BOARD_TABLE";
export const UPDATE_BOARD_TABLE = "UPDATE_BOARD_TABLE";
export const INITIALIZE_PLANNER = "INITIALIZE_PLANNER";
